# Generated by Django 4.0.1 on 2022-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_ID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
